CREATE DATABASE IF NOT EXISTS tasksManager;
USE tasksManager;

CREATE TABLE IF NOT EXISTS Project (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  startDate DATE,
  endDate DATE
);

CREATE TABLE IF NOT EXISTS User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Team (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT
);

ALTER TABLE Project ADD COLUMN teamId INT NULL;
ALTER TABLE Project ADD CONSTRAINT FK_team FOREIGN KEY (teamId) REFERENCES Team(id);
